spring:
  profiles:
    active:
     - dev
---
spring:
     profiles: dev
     application:
       name: microservicecloud-config-supermap-dev
---
spring:
     profiles: test
     application: microservicecloud-config-supermap-test